[pyprland]
plugins = [
  "scratchpads",
]


[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm nvim --noplugin todo.md"
class = "kitty-dropterm"
size = "50% 60%"
max_size = "1920px 100%"
margin = 50
